# Generated by Django 4.2.16 on 2025-04-14 17:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="custom_seo_title",
            field=models.CharField(
                blank=True, help_text="Custom SEO title (optional)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="features",
            field=wagtail.fields.StreamField(
                [("feature", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("text", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="features_title",
            field=models.CharField(default="Innovative Features", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(default="Get Early Access", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(
                default="Curious, eager, and always ready to help. Experience the next generation of AI assistance.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Shoshin: The AI Chatbot with a Beginner's Mind", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_button_text",
            field=models.CharField(default="Notify Me", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_text",
            field=models.TextField(
                default="Be the first to know when Shoshin launches. Sign up get notified when we launch and receive exclusive early access along with our exclusive newsletter for free!"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_title",
            field=models.CharField(default="Stay Updated", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners",
            field=wagtail.fields.StreamField(
                [("partner", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("logo", 0), ("name", 1), ("url", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners_text",
            field=models.TextField(
                default="Shoshin is supported by industry leaders and trusted partners who believe in the future of AI."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners_title",
            field=models.CharField(
                default="Backed by Leading Innovators", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_cta_link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_cta_text",
            field=models.CharField(default="Get Started", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_description",
            field=models.TextField(
                default="Get all these advanced features for less than $10/month. Enjoy premium AI without the premium price tag."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_features",
            field=wagtail.fields.StreamField(
                [("feature", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.CharBlock", (), {})},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_subtitle",
            field=models.CharField(default="Early Bird Offer", max_length=200),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pricing_title",
            field=models.CharField(
                default="Transparent & Affordable Pricing", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_description",
            field=models.TextField(
                blank=True, help_text="Custom SEO description (optional)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials",
            field=wagtail.fields.StreamField(
                [("testimonial", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0), ("author", 1), ("role", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_title",
            field=models.CharField(default="What People Are Saying", max_length=100),
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Shoshin AI", max_length=100)),
                (
                    "default_description",
                    models.TextField(
                        default="Shoshin: The AI Chatbot with a Beginner's Mind. Curious, eager, and always ready to help."
                    ),
                ),
                ("og_type", models.CharField(default="website", max_length=20)),
                (
                    "twitter_card",
                    models.CharField(default="summary_large_image", max_length=20),
                ),
                (
                    "twitter_site",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "default_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
            },
        ),
    ]
