# Generated by Django 4.2.20 on 2025-04-14 17:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("home", "0004_alter_homepage_options_remove_homepage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="features_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="newsletter_button_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="newsletter_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="newsletter_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_cta_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="testimonials_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="default_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="site_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=100)),
                ("hero_subtitle", models.CharField(blank=True, max_length=200)),
                ("hero_cta_text", models.CharField(blank=True, max_length=50)),
                ("hero_cta_link", models.URLField(blank=True)),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("feature", 6),
                            ("testimonial", 8),
                            ("quote", 9),
                            ("cta", 12),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "full title"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            5: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 3), ("title", 4), ("text", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 5), ("author", 4), ("role", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            10: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 4),
                                        ("text", 10),
                                        ("button_text", 4),
                                        ("button_link", 11),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for social media sharing (Facebook, LinkedIn)",
                        max_length=100,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True,
                        help_text="Custom description for social media sharing",
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for Twitter sharing",
                        max_length=100,
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, help_text="Custom description for Twitter sharing"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Override canonical URL if this page has a preferred URL",
                    ),
                ),
                (
                    "enable_schema_org",
                    models.BooleanField(
                        default=True, help_text="Enable Schema.org structured data"
                    ),
                ),
                (
                    "schema_org_type",
                    models.CharField(
                        default="WebPage",
                        help_text="Type of Schema.org entity (e.g., WebPage, Article, Product)",
                        max_length=100,
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        help_text="When this content was first published",
                        null=True,
                    ),
                ),
                (
                    "update_date",
                    models.DateField(
                        blank=True,
                        help_text="When this content was last significantly updated",
                        null=True,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search engines",
                        max_length=255,
                    ),
                ),
                (
                    "show_breadcrumbs",
                    models.BooleanField(
                        default=True, help_text="Show breadcrumb navigation"
                    ),
                ),
                (
                    "show_share_buttons",
                    models.BooleanField(
                        default=True, help_text="Show social sharing buttons"
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing (ideally 1200×630px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "twitter_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for Twitter sharing (ideally 1200×600px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
