# Generated by Django 4.2.20 on 2025-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_features_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.URLField(blank=True, default="https://example.com"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pricing_cta_link",
            field=models.URLField(blank=True, default="https://example.com"),
        ),
    ]
