# Generated by Django 4.2.20 on 2025-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_hero_cta_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="hero_cta_link",
            field=models.URLField(blank=True, default="https://example.com"),
        ),
    ]
